# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_by', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('traveled_from', models.DateTimeField(verbose_name='traveled_from')),
                ('traveled_to', models.DateTimeField(verbose_name='traveled_to')),
            ],
        ),
    ]
