# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='destination',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
